# yourorg/helm-chart-repository/.github/workflows/update-index.yml
name: Update Index

on:
  push:
    branches: [ master ]
    paths:
      - '**.tgz'

  workflow_dispatch:
    branches: [ master ]
    paths:
      - '**.tgz'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Helm Installation
        uses: azure/setup-helm@v1.1
        with:
          version: v3.7.0
      - name: Update Index
        run: |
          helm repo index .
      - name: Update git
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'index.yaml'
          commit_message: 'Update index'
          
