# yourorg/helm-chart-repository/.github/workflows/update-index.yml
name: Update Index

on:
  push:
    branches: [ master ]
    paths:
      - '**.tgz'

  workflow_dispatch:
    branches: [ master ]
    paths:
      - '**.tgz'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Helm Installation
        uses: azure/setup-helm@v1.1
        with:
          version: v3.7.0
      - name: Update Index
        run: |
          helm repo index .
          git config --global user.email "rohitthadani@duck.com"
          git config --global user.name "Rohit Thadani"
          git add index.yaml
          git commit -m "Update chart index"
          git push
